### ISSUE TITLE
Question about A1/A2 alleles for munge_sumstat.py

### ISSUE THREAD

**Issue by jhchung** [bulik/ldsc#133]
I am not clear on how `munge_sumstats.py` interprets the A1 and A2 labels.

For my data, the alternate allele is always the effect allele. For the following command,

    munge_sumstats.py \
        --a1 ref \
        --a2 alt \
        --signed-sumstats Z,0 \
        --p pval \
        --sumstats <sumstat_file> \
        --out <output_file>

The log file from `munge_sumstats.py` states

> alt: Allele 2, interpreted as non-ref allele for signed sumstat
> ref: Allele 1, interpreted as ref allele for signed sumstat

But the Heritability and Genetic Correlation Wiki page lists

* Allele 1 (effect allele)
* Allele 2 (non-effect allele)

Which is not what I intended. 

Any help understanding how to interpret the A1/A2 allele and how to assign the parameters would be great.

----

Also, looking though the python script to get a better idea of what is going on, I noticed something on line 396 of `munge_sumstats.py`, should

        [args.frq, 'FRQ', '--nstudy'],

be changed to 

        [args.frq, 'FRQ', '--frq'],

to correctly capture the `--frq` parameter?

Thanks,
-Jonathan

**Comment by rkwalters** [comment]
Hi Jonathan,

The a1 field is interpreted as the effect allele and the a2 field is interpreted as the non-effect allele. In other words, it is assumed that the sign of the signed sumstats corresponds to the direction of effect associated with the a1 allele.

Part of the confusion here is that the "reference" allele is an overloaded term in genetics. It could refer to the human genome reference (as in your case with ref/alt) or could refer to the choice of allele to count copies of when coding SNPs 0/1/2 for regression (i.e. the effect allele). The latter usage has become somewhat less common, but can be seen in places relevant to ldsc input such as in the impact of the --reference-allele flag in plink <http://zzz.bwh.harvard.edu/plink/dataman.shtml#refallele> or in the usage of refAllele in the METAL documentation <https://genome.sph.umich.edu/wiki/METAL_Documentation#Input_File_Recommendations>. That said, it's possible that changing the log info for a1 to describe it as the effect allele rather than the ref allele could reduce confusion; will give this some thought.

As far as the args.frq line, its possible we should change that for code clarity (or just remove it) but it actually has no functional impact. If you check the code that third field of the entries in cname_options in never used.

Cheers,
Raymond

**Comment by jhchung** [comment]
Hi Raymond,

Thanks for the clarification. It looks like I should change the a1/a2 allele flags in my example command.

Best,
-Jonathan

**Comment by complexgenome** [comment]
@jhchung @rkwalters 
Sorry to revive seven years old thread. I run into this message sadly. 
I've flipped sign of Beta, changed effect to A2 instead of A1 where A1 is effect itself yet none of these measures help me stop this message.

I think I'd like to know does the LDSC still consider A1 as effect or not despite this ALT/REF flip?
