### ISSUE TITLE
Why large Z score are removed

### ISSUE THREAD

**Issue by SichengH** [bulik/ldsc#134]
Hello, 

This is a question rather than an issue. 

I have some GWAS summary data, but after using munge_sumstats.py I found that a lot of my data which is removed is "good" data with large Z (Beta/SE), some of them even carrier significant information. 

I don't quite understand the code. Just wondering did I do something wrong? 

Please help,
Sicheng Hao

**Comment by rkwalters** [comment]
Hi,

The munge_sumstats.py script removes variants for a few different reasons:

- Invalid p-value (i.e. not between 0 and 1)
- Imputation INFO < 0.9 (if INFO field included; threshold can be adjusted with --info-min)
- MAF < .01 (if allele frequency is provided; threshold can be adjusted with --maf-min)
- Insufficient N (compared to other SNPs in the GWAS data; can be adjusted with --n-min)
- Insufficient number of contributing studies (not used by default; specified by --nstudy and --nstudy-min)
- Variant is not a SNP (e.g. indels)
- Variant is strand ambiguous
- Variant is not present in the --merge-alleles file, if provided (matched based on rsids)

The log output from running munge_sumstats.py should tell you how many variants are being excluded based on each of these criteria. In general, it will be normal to have a large number of variants dropped from input GWAS summary data by munge_sumstats.py if you're using the standard w_hm3.snplist file. That file restricts to ~1.2 million HapMap3 sites that are expected to be well covered in most GWAS. The MAF, INFO, and strand ambiguous filters may also drop noteworthy numbers of SNPs depending on what filtering has been done previously for the GWAS summary data.

As long as you have ~1 million SNPs remaining after munge_sumstats.py you should be fine for ldsc analyses. Because of how LD score regression works it's more important to have a representative set of high-quality genome-wide variants included in the analysis rather than retaining every SNP from the GWAS data. If however you are ending with substantially less than 1 million SNPs then you may want to evaluate whether there are other issues from the filtering done my munge_sumstats.py.

Cheers,
Raymond
