### ISSUE TITLE
alueError: Too many signed sumstat columns. Specify which to ignore with the --ignore flag.

### ISSUE THREAD

**Issue by emiled16** [bulik/ldsc#238]
Hello, I am getting the following error, can someone please help me?
`Traceback (most recent call last):
  File "/Users/emdim/Desktop/ldsc/munge_sumstats.py", line 745, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "/Users/emdim/Desktop/ldsc/munge_sumstats.py", line 608, in munge_sumstats
    'Too many signed sumstat columns. Specify which to ignore with the --ignore flag.')
ValueError: Too many signed sumstat columns. Specify which to ignore with the --ignore flag.`

Thanks a lot

**Comment by zubiamansoor** [comment]
Hi,

I had the same error because I had Odds Ratio as well as Z-score in my files. That confuses the script as it does not know which one to pick. I solved this problem by using the flag --ignore OR. This tells munge_sumstats.py to ignore Odds Ratio as the signed summary statistic and specifies Z-score instead. In the absence of this, the system raises an error that too many signed statistics were present. It might be a good idea to see what columns you have and if there are more than 1 signed summary stat. In that case, just ignore the one you don't want it to read. Hope that helps!

Best,
Zubia.

**Comment by emiled16** [comment]
Thank you so much, Zubia, I appreciate a lot.
Best,
Emile
