### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by oh-jinwoo94** [bulik/ldsc#250]
Hello!

I'm going through the tutorial  on (https://github.com/bulik/ldsc/wiki/Partitioned-Heritability), and I'm getting the error message at the bottom when I run the following command line (copied from the tutorial):

python ldsc.py 
	--h2 BMI.sumstats.gz\
	--ref-ld-chr baseline.\ 
	--w-ld-chr weights.\
	--overlap-annot\
	--frqfile-chr 1000G.mac5eur.\
	--out BMI_baseline

================================
Analysis finished at Thu Dec 10 02:11:19 2020
Total time elapsed: 1.38s
Traceback (most recent call last):
  File "ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/mnt/t/data0/joh27/tools/ldsc/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "/mnt/t/data0/joh27/tools/ldsc/ldscore/sumstats.py", line 243, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/mnt/t/data0/joh27/tools/ldsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/mnt/t/data0/joh27/tools/ldsc/ldscore/sumstats.py", line 152, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/mnt/t/data0/joh27/tools/ldsc/ldscore/parse.py", line 103, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/mnt/t/data0/joh27/tools/ldsc/ldscore/parse.py", line 147, in ldscore
    first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range
============================================

I used the ldsc environment as described in the tutorial, but I keep getting the same error message.

**Comment by xueenci** [comment]
Hi, 

I met the same bug, i want to konw if u have fix this  and how ?

Thank you !!

**Comment by oh-jinwoo94** [comment]
I have not fixed this problem yet :/

**Comment by jek4zy** [comment]
I have been getting the same error for about a week or two now.

**Comment by choishingwan** [comment]
A few things to try:
1. Proper indentation / new line to see if it is a script error

```
python ldsc.py \
        --h2 BMI.sumstats.gz \
        --ref-ld-chr baseline. \
        --w-ld-chr weights. \
        --overlap-annot \
        --frqfile-chr 1000G.mac5eur. \
        --out BMI_baseline
```

2. Check the baseline files, the 1000G.mac5eur file and your summary statistics and make sure they only contain chromosome 1 - 22, maybe that can help/ (Also, maybe use 1-22, instead of chr1,chr2,...,chr22) and see if that helps. Those are my 2 cents

**Comment by jek4zy** [comment]
I am running:
python2.7 ldsc.py --rg sle.sumstats.gz,cad.sumstats.gz --w-ld-chr eur_w_ld_ch --ref-ld-chr eur_w_ld_chr --out cad_sle --no-check-alleles

and getting the same error: 
Reading reference panel LD Score from eur_w_ld_chr[1-22] ... (ldscore_fromlist)
Traceback (most recent call last):
  File "ldsc.py", line 642, in <module>
    sumstats.estimate_rg(args, log)
  File "/Users/user/ldsc/ldscore/sumstats.py", line 397, in estimate_rg
    alleles=True, dropna=True)
  File "/Users/user/ldsc/ldscore/sumstats.py", line 243, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/Users/user/ldsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/Users/user/ldsc/ldscore/sumstats.py", line 152, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/Users/user/ldsc/ldscore/parse.py", line 103, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/Users/use/ldsc/ldscore/parse.py", line 147, in ldscore
    first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range

Traceback (most recent call last):
  File "ldsc.py", line 642, in <module>
    sumstats.estimate_rg(args, log)
  File "/Users/user/ldsc/ldscore/sumstats.py", line 397, in estimate_rg
    alleles=True, dropna=True)
  File "/Users/user/ldsc/ldscore/sumstats.py", line 243, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/Users/user/ldsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/Users/user/ldsc/ldscore/sumstats.py", line 152, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/Users/user/ldsc/ldscore/parse.py", line 103, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/Users/user/ldsc/ldscore/parse.py", line 147, in ldscore
    first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range

**Comment by cripenam** [comment]
you have to be careful on where are you setting, your data. 
just don't copy paste

python ldsc.py
--h2 BMI.sumstats.gz
--ref-ld-chr baseline.\
--w-ld-chr weights.
--overlap-annot
--frqfile-chr 1000G.mac5eur.
--out BMI_baseline

for example, in my computer this code looks like this :

python ldsc.py 
--out BMI_baseline 
--h2 BMI.sumstats.gz 
--ref-ld-chr /Users/lab/Desktop/ldsc/baseline/baseline. 
--w-ld-chr /Users/lab/Desktop/ldsc/weights_hm3_no_hla/weights.  
--overlap-annot 
--frqfile-chr /Users/lab/Desktop/ldsc/1000G_frq/1000G.mac5eur.

The reason why in the tutorial they write 
--ref-ld-chr baseline.\
--w-ld-chr weights.

is because they expect you to have all the files in the same folder, but theorically if you are downloading this files, you will have a folder called "weights_hm3_no_hla" another one "baseline" , so if you write the direction where those folders are: in my case: /Users/lab/Desktop/ldsc/baseline/baseline.    This is telling ldsc program that the baseline folder contains some files that start wtih "baseline." and although they are divided into chromosomes, in this case all of them should be used. 

I ran with the same problem, I just didn't realized that i needed to point correctly to ldsc where the files are. 

Hope it helps 

"note that the baseline, weights and 100g files should be not in gz format " I use them as unzipped, as folders"

**Comment by oh-jinwoo94** [comment]
Seems to work for me now! I unzipped the folders appropriately as @cripenam  suggested.

**Comment by oh-jinwoo94** [comment]
Seems to work for me now! I unzipped the folders appropriately as @cripenam  suggested.

**Comment by xiechengyong123** [comment]
> 

Hello! In my personal experience this is probably due to the fact that you are using the wrong parameters,
If you use such parameters you will get the result you described above:
./ldsc.py  --h2  SAIGE_MACge20_cleaned.sumstats.gz \ 
               --ref-ld-chr ./ldsc/reference/eur_w_ld_chr/  \
               --w-ld-chr  ./ldsc/reference/w_hm3.snplist  \
               --out SAIGE_MACge20_cleaned.sumstats_h2

Modify the --w-ld-chr parameter to run properly, e.g.
               --w-ld-chr . /ldsc/reference/eur_w_ld_chr/ 

link: https://github.com/bulik/ldsc/wiki/Heritability-and-Genetic-Correlation#tldr

**Comment by CaoLuolong** [comment]
=======================================
I think this is beacuse you have a loss of "/" in the workpath of "--ref-ld-chr", and you can try this:
 ./ldsc.py --h2 pgc.sumstats.gz --ref-ld-chr eur_w_ld_chr/ --w-ld-chr eur_w_ld_chr/ --out pgc_h2
