### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/var/www/ldhub/ldhub_web/static/sumstats/ldhub_100_sumstat_full_HC_comp1.txt.5fed644d-592e-48c9-8c27-addf36e7e3d0.sumstats.gz'

### ISSUE THREAD

**Issue by emiled16** [bulik/ldsc#260]
I am running an analysis on one of my summary statistic  on the ldhub server (http://ldsc.broadinstitute.org/).
I am getting the following message that says it cannot find the file, however, I just have to upload my summary stat.

Here is the log file:

__________________________________________________________________

    *********************************************************************
    * LD Score Regression (LDSC)
    * Version 1.0.0
    * (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
    * Broad Institute of MIT and Harvard / MIT Department of Mathematics
    * GNU General Public License v3
    *********************************************************************
    Call: 
    ./ldsc.py \
    --h2 /var/www/ldhub/ldhub_web/static/sumstats/ldhub_100_sumstat_full_HC_comp1.txt.5fed644d-592e-48c9-8c27-addf36e7e3d0.sumstats.gz \
    --ref-ld-chr /root/ldsc/eur_w_ld_chr/ \
    --out /var/www/ldhub/ldhub_web/static/sumstats/ldhub_100_sumstat_full_HC_comp1.txt.5fed644d-592e-48c9-8c27-addf36e7e3d0-h2 \
    --w-ld-chr /root/ldsc/eur_w_ld_chr/ 
    
    Beginning analysis at Tue Jan 19 00:40:42 2021
    Reading summary statistics from /var/www/ldhub/ldhub_web/static/sumstats/ldhub_100_sumstat_full_HC_comp1.txt.5fed644d-592e-48c9-8c27-addf36e7e3d0.sumstats.gz ...
    Traceback (most recent call last):
      File "/root/ldsc/ldsc.py", line 628, in <module>
        sumstats.estimate_h2(args, log)
      File "/root/ldsc/ldscore/sumstats.py", line 260, in estimate_h2
        args, log, args.h2)
      File "/root/ldsc/ldscore/sumstats.py", line 236, in _read_ld_sumstats
        sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)
      File "/root/ldsc/ldscore/sumstats.py", line 162, in _read_sumstats
        sumstats = ps.sumstats(fh, alleles=alleles, dropna=dropna)
      File "/root/ldsc/ldscore/parse.py", line 79, in sumstats
        x = read_csv(fh, usecols=usecols, dtype=dtype_dict, compression=compression)
      File "/root/ldsc/ldscore/parse.py", line 20, in read_csv
        return pd.read_csv(fh, delim_whitespace=True, na_values='.', **kwargs)
      File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 498, in parser_f
        return _read(filepath_or_buffer, kwds)
      File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 275, in _read
        parser = TextFileReader(filepath_or_buffer, **kwds)
      File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 590, in __init__
        self._make_engine(self.engine)
      File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 731, in _make_engine
        self._engine = CParserWrapper(self.f, **self.options)
      File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 1103, in __init__
        self._reader = _parser.TextReader(src, **kwds)
      File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3246)
      File "pandas/parser.pyx", line 556, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:5583)
      File "/usr/lib64/python2.7/gzip.py", line 94, in __init__
        fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
    IOError: [Errno 2] No such file or directory: '/var/www/ldhub/ldhub_web/static/sumstats/ldhub_100_sumstat_full_HC_comp1.txt.5fed644d-592e-48c9-8c27-addf36e7e3d0.sumstats.gz'
    
    Analysis finished at Tue Jan 19 00:40:42 2021
    Total time elapsed: 0.03s
__________________________________________

Could you please guide me through?
Thanks

**Comment by YULING52** [comment]
Hello, I also met the same problem.  Would you please tell me how you solved it?

**Comment by emiled16** [comment]
first, you need to make sure to update a text file with the requirements that are stated. Second, I suggest uploading one file at a time and wait to see the message saying the computation has started before uploading another one.  When I uploaded more than 5 files I was getting an error. I suggest not exceed 5 files at a time.

**Comment by YULING52** [comment]
Hi!

Thank you very much for your reply.

In fact, I did upload one file at a time, because I only have one file needed to be uploaded.

 

The file I have (mditry_3.txt) was like this:

 

chr bp a2 a1 snpid N BETA SE L95 U95 STAT pval

1 713977 C T rs74512038 2691 0.4648 1.342 -2.165 3.095 0.3464 0.729

1 751343 T A rs28544273 2691 -0.01603 0.9547 -1.887 1.855 -0.01679 0.9866

1 751488 G GA . 2691 0.05062 0.963 -1.837 1.938 0.05257 0.9581

1 751756 T C rs28527770 2691 -0.01603 0.9547 -1.887 1.855 -0.01679 0.9866

1 753541 G A rs2073813 2691 0.2627 0.8747 -1.452 1.977 0.3003 0.7639

1 756434 G C rs61768170 2691 -0.01603 0.9547 -1.887 1.855 -0.01679 0.9866

1 759293 T A rs10157329 2691 -0.01603 0.9547 -1.887 1.855 -0.01679 0.9866

1 762485 C A rs12095200 2691 -0.1535 1.016 -2.145 1.838 -0.151 0.88

1 764191 T G rs7515915 2691 -0.01603 0.9547 -1.887 1.855 -0.01679 0.9866

1 766007 A C rs61768174 2691 0.146 1.048 -1.907 2.199 0.1393 0.8892

1 769138 CAT C . 2691 -0.03889 0.9537 -1.908 1.83 -0.04077 0.9675

1 769223 C G rs60320384 2691 -0.03889 0.9537 -1.908 1.83 -0.04077 0.9675

1 771967 G A rs59066358 2691 -0.3087 0.9796 -2.229 1.611 -0.3152 0.7527

1 775181 A G rs61768182 2691 -0.03889 0.9537 -1.908 1.83 -0.04077 0.9675

1 775659 A G rs2905035 2691 -0.08501 0.9532 -1.953 1.783 -0.08918 0.9289

1 777122 A T rs2980319 2691 -0.08501 0.9532 -1.953 1.783 -0.08918 0.9289

1 778745 A G rs1055606 2691 -0.03889 0.9537 -1.908 1.83 -0.04077 0.9675

1 779322 A G rs4040617 2691 -0.03889 0.9537 -1.908 1.83 -0.04077 0.9675

1 780785 T A rs2977612 2691 0.2756 0.8022 -1.297 1.848 0.3435 0.7312

1 781845 A G rs61768199 2691 0.03636 0.9639 -1.853 1.926 0.03772 0.9699

1 782981 C T rs6594026 2691 0.2308 0.9102 -1.553 2.015 0.2535 0.7999

1 783318 A G rs6686696 2691 -0.03889 0.9537 -1.908 1.83 -0.04077 0.9675

1 785050 G A rs2905062 2691 0.2026 0.761 -1.289 1.694 0.2662 0.7901

1 785989 T C rs2980300 2691 0.2026 0.761 -1.289 1.694 0.2662 0.7901

1 786995 G A rs61768202 2691 -0.03889 0.9537 -1.908 1.83 -0.04077 0.9675

1 787262 C G rs2905056 2691 0.09745 0.9471 -1.759 1.954 0.1029 0.9181

1 787399 G T rs2905055 2691 0.3103 0.8091 -1.275 1.896 0.3836 0.7013

1 787606 G T rs3863622 2691 -0.03889 0.9537 -1.908 1.83 -0.04077 0.9675

1 787685 G T rs2905054 2691 0.2367 0.761 -1.255 1.728 0.311 0.7558

…….

22 51216149 C A rs373165495 2691 -0.2638 1.197 -2.611 2.083 -0.2203 0.8256

22 51216564 T C rs9616970 2691 -0.2638 1.197 -2.611 2.083 -0.2203 0.8256

22 51219006 G A rs28729663 2691 -0.1363 0.9745 -2.046 1.774 -0.1399 0.8888

22 51227891 G A rs6010091 2691 0.3026 0.7124 -1.094 1.699 0.4248 0.671

22 51233045 A G rs4050248 2691 -0.5999 1.312 -3.17 1.971 -0.4574 0.6474

 

This file (mditry 3.txt) has 5,870,539 lines.

The file I uploaded was mditry_3.zip, which only has one txt file——mditry_3.txt:

 

 

But I still got an error. I reviewed following document requirements several times but did not find anything wrong. Maybe there was something wrong with my file format and I did not find it.

 

Would you please help me to find out what the problem was? Did my file format not meet the requirements?

 

 

This is QC log:

 

*********************************************************************

* LD Score Regression (LDSC)

* Version 1.0.0

* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane

* Broad Institute of MIT and Harvard / MIT Department of Mathematics

* GNU General Public License v3

*********************************************************************

Call:

./munge_sumstats.py \

--out /var/www/ldhub/ldhub_web/static/sumstats/mditry_3.txt.3b8107f2-8cc5-4ad7-8af2-d1de02091435 \

--merge-alleles /root/ldsc/w_hm3.noMHC.snplist \

--sumstats /tmp/uploaded_files/mditry_3.txt.3b8107f2-8cc5-4ad7-8af2-d1de02091435

 

Interpreting column names as follows:

snpid:     Variant ID (e.g., rs number)

N:    Sample size

a1:  Allele 1, interpreted as ref allele for signed sumstat.

pval: p-Value

BETA:     [linear/logistic] regression coefficient (0 --> no effect; above 0 --> A1 is trait/risk increasing)

a2:  Allele 2, interpreted as non-ref allele for signed sumstat.

 

Reading list of SNPs for allele merge from /root/ldsc/w_hm3.noMHC.snplist

Read 1215001 SNPs for allele merge.

Reading sumstats from /tmp/uploaded_files/mditry_3.txt.3b8107f2-8cc5-4ad7-8af2-d1de02091435 into memory 5000000 SNPs at a time.

Read 5870539 SNPs from --sumstats file.

Removed 4307598 SNPs not in --merge-alleles.

Removed 663853 SNPs with missing values.

Removed 0 SNPs with INFO <= 0.9.

Removed 0 SNPs with MAF <= 0.01.

Removed 0 SNPs with out-of-bounds p-values.

Removed 419 variants that were not SNPs or were strand-ambiguous.

898669 SNPs remain.

Removed 85 SNPs with duplicated rs numbers (898584 SNPs remain).

 

ERROR converting summary statistics:

 

Traceback (most recent call last):

  File "/root/ldsc/munge_sumstats.py", line 649, in munge_sumstats

    dat = process_n(dat, args, log)

  File "/root/ldsc/munge_sumstats.py", line 324, in process_n

    n_min = args.n_min if args.n_min else dat.N.quantile(0.9) / 1.5

  File "/usr/lib64/python2.7/site-packages/pandas/core/series.py", line 1286, in quantile

    return self._maybe_box(lambda values: multi(values, q), dropna=True)

  File "/usr/lib64/python2.7/site-packages/pandas/core/series.py", line 2234, in _maybe_box

    result = func(values)

  File "/usr/lib64/python2.7/site-packages/pandas/core/series.py", line 1286, in <lambda>

    return self._maybe_box(lambda values: multi(values, q), dropna=True)

  File "/usr/lib64/python2.7/site-packages/pandas/core/series.py", line 1284, in multi

    return _quantile(values, qs*100)

  File "/usr/lib64/python2.7/site-packages/numpy/lib/function_base.py", line 3268, in percentile

    interpolation=interpolation)

  File "/usr/lib64/python2.7/site-packages/numpy/lib/function_base.py", line 2997, in _ureduce

    r = func(a, **kwargs)

  File "/usr/lib64/python2.7/site-packages/numpy/lib/function_base.py", line 3385, in _percentile

    x1 = take(ap, indices_below, axis=axis) * weights_below

TypeError: can't multiply sequence by non-int of type 'float'

 

 

Conversion finished at Mon Mar  1 01:05:46 2021

Total time elapsed: 32.33s

 

 

 

This is SNP heritability results:

*********************************************************************

* LD Score Regression (LDSC)

* Version 1.0.0

* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane

* Broad Institute of MIT and Harvard / MIT Department of Mathematics

* GNU General Public License v3

*********************************************************************

Call:

./ldsc.py \

--h2 /var/www/ldhub/ldhub_web/static/sumstats/mditry_3.txt.3b8107f2-8cc5-4ad7-8af2-d1de02091435.sumstats.gz \

--ref-ld-chr /root/ldsc/eur_w_ld_chr/ \

--out /var/www/ldhub/ldhub_web/static/sumstats/mditry_3.txt.3b8107f2-8cc5-4ad7-8af2-d1de02091435-h2 \

--w-ld-chr /root/ldsc/eur_w_ld_chr/

 

Beginning analysis at Mon Mar  1 01:05:46 2021

Reading summary statistics from /var/www/ldhub/ldhub_web/static/sumstats/mditry_3.txt.3b8107f2-8cc5-4ad7-8af2-d1de02091435.sumstats.gz ...

Traceback (most recent call last):

  File "/root/ldsc/ldsc.py", line 628, in <module>

    sumstats.estimate_h2(args, log)

  File "/root/ldsc/ldscore/sumstats.py", line 260, in estimate_h2

    args, log, args.h2)

  File "/root/ldsc/ldscore/sumstats.py", line 236, in _read_ld_sumstats

    sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)

  File "/root/ldsc/ldscore/sumstats.py", line 162, in _read_sumstats

    sumstats = ps.sumstats(fh, alleles=alleles, dropna=dropna)

  File "/root/ldsc/ldscore/parse.py", line 79, in sumstats

    x = read_csv(fh, usecols=usecols, dtype=dtype_dict, compression=compression)

  File "/root/ldsc/ldscore/parse.py", line 20, in read_csv

    return pd.read_csv(fh, delim_whitespace=True, na_values='.', **kwargs)

  File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 498, in parser_f

    return _read(filepath_or_buffer, kwds)

  File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 275, in _read

    parser = TextFileReader(filepath_or_buffer, **kwds)

  File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 590, in __init__

    self._make_engine(self.engine)

  File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 731, in _make_engine

    self._engine = CParserWrapper(self.f, **self.options)

  File "/usr/lib64/python2.7/site-packages/pandas/io/parsers.py", line 1103, in __init__

    self._reader = _parser.TextReader(src, **kwds)

  File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3246)

  File "pandas/parser.pyx", line 556, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:5583)

  File "/usr/lib64/python2.7/gzip.py", line 94, in __init__

    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')

IOError: [Errno 2] No such file or directory: '/var/www/ldhub/ldhub_web/static/sumstats/mditry_3.txt.3b8107f2-8cc5-4ad7-8af2-d1de02091435.sumstats.gz'

 

Analysis finished at Mon Mar  1 01:05:46 2021

Total time elapsed: 0.0s

















| |
重医-俞灵 （男）
|
|
18324184161@163.com
|
签名由网易邮箱大师定制
On 3/3/2021 05:41，emiled16<notifications@github.com> wrote：

first, you need to make sure to update a text file with the requirements that are stated. Second, I suggest uploading one file at a time and wait to see the message saying the computation has started before uploading another one. When I uploaded more than 5 files I was getting an error. I suggest not exceed 5 files at a time.
