### ISSUE TITLE
Missing tutorial/FAQ links

### ISSUE THREAD

**Issue by mkanai** [bulik/ldsc#27]
Hi. Thank you for providing a great software.

I just found out the links for the tutorial/FAQ in `README.md` were 404. They should be the links to the wiki, but they are currently pointing to `./tutorials` or `./docs/FAQ`.

Another issue I just found is that inconsistent explanation in the tutorial.
In the ["Estimating Genetic Correlation" section](https://github.com/bulik/ldsc/wiki/Genetic-Correlation#--ref-ld-chr), `--ref-ld-chr` takes `eur_ref_ld_chr/` but the explanation says `eur_w_ld_chr/...`.

>
 typing `--ref-ld-chr eur_ref_ld_chr/` tells `ldsc` to use the files `eur_w_ld_chr/1.l2.ldscore, ... , eur_w_ld_chr/22.l2.ldscore.`

Throughout the document, you sometimes mix-up the two, and it will possibly confuse beginners.

**Comment by bulik** [comment]
Thanks for catching these errors.

FYI using the `eur_w_ld_chr/` LD Scores as the argument to both `--ref-ld-chr` and `--w-ld-chr` is intentional. For some reason, these LD Scores (which are sum r^2 with the sum taken over HapMap3 SNPs) tend to give more reasonable results (LD Score regression intercepts closer to 1 in studies where I believe there is little to no confounding from population stratification). This is probably because the 1000 Genomes LD Scores (sum r^2 taken over all 1000 Genomes SNPs) give too much weight to low MAF SNPs, and HapMap 3 LD Scores given a little more weight to common variants.

**Comment by mkanai** [comment]
Thank you for additional information. Really helpful!
