### ISSUE TITLE
Genome build of tutorial data?

### ISSUE THREAD

**Issue by PeteHaitch** [bulik/ldsc#63]
I'd just like to confirm that the data available from https://data.broadinstitute.org/alkesgroup/LDSCORE/ (and used in the tutorial) use GRCh37/hg19 co-ordinates? Checking the co-ordinates of a few SNPs suggests this is true, but I haven't done this systematically.
Thanks

**Comment by rkwalters** [comment]
Hi Peter,
Yes, the reference files use hg19 coordinates.

The impact of build on ldsc is probably limited. Ldsc uses coordinates primarily for relative position (splitting chromosomes, sorting genomic order, computing LD within a given kb or cM distance) rather than absolute locations. Matching SNPs to the reference relies on rsIDs rather than chr:bp locations.

Cheers,
Raymond

**Comment by PeteHaitch** [comment]
Thanks, Raymond. That's what I suspected, but it's good to have confirmation.
