### ISSUE TITLE
Problems with external data source

### ISSUE THREAD

**Issue by mhsteppan** [bulik/ldsc#65]
Hi,
I have a problem with an external data source on Personality:
https://www.dropbox.com/s/df3bifmk238ks2y/GPC-1.BigFiveNEO.zip?dl=0

the command munge_sumstats.py does not work properly due to reasons I dont understand. There is a column named OR (odds ratio), the mean is close to 0. What needs to be done with this data source, in order to use it?
cheers,
martin

**Comment by rkwalters** [comment]
Hi Martin,

Could you post the log from munge_sumstats.py with whatever error message you are getting?

Thanks,
Raymond

**Comment by mhsteppan** [comment]
![image](https://cloud.githubusercontent.com/assets/8658828/21024680/b9acfda2-bd85-11e6-9edc-0eb94647a68a.png)

**Comment by rkwalters** [comment]
Hi Martin,

It looks like this error might be caused by having an empty column? Could result from either having more header fields than data fields, or by having a mis-labelled column that leads to all variants being filtered out. 

Since the GPC-1 files don’t have a header in the public download some preprocessing is required to add the column labels, so I suspect that’s where something has gone awry.

Cheers,
Raymond
