### ISSUE TITLE
--h2 w/ suffix

### ISSUE THREAD

**Issue by hilaryf** [bulik/ldsc#8]
would be nice if --h2 took the file name instead of prefix.

**Comment by bulik** [comment]
this feature is a leftover from when we had .chisq/.allele filesets. it would be nice to make this change without breaking backwards compatibility, so that i don't have to go rewrite all the shell scripts i have that call --h2 and --rg.

one option would be to have ldsc check for .chisq.gz and remove .chisq.gz if it finds it. the (minor) downside is that this could in theory be ambiguous, e.g., if you have foo.chisq.chisq and foo.chisq in the same directory and you call --h2 foo.chisq, which file do you mean? I think this is unlikely to be a real problem, so we can just mention not to do this in the tutorial. 

Actually, on second thoughts, the current setup is ambiguous -- if you have foo.chisq, foo.chisq.gz and foo.pickle in the same directory, which will ldsc read (pickle, then .chisq.gz then .chisq -- but this isn't documented anywhere yet). Now I'm leaning towards requiring the full filename (bonus: works with ls and tab-complete). 

Thoughts?

**Comment by bulik** [comment]
closing this issue; --rg and --h2 now take full filenames in dev, and this will be the standard for v1.0.0
