### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pfsulliv** [bulik/ldsc#9]
--h2-observed-to-liabiity FN

where FN is a text file. Input has any number of rows, each row has label (like mdd_old), h2_obs, K, Ncase, Ncontrol. Output repeats the input and adds h2_liab. 

Others will need this too, and would be bad if people reported h2-obs as h2-liability in papers.

**Comment by bulik** [comment]
This seems like something that would work better as a standalone script, rather than a feature of ldsc (also we haven't focused much on heritability estimation so far, because almost all of the public GWAS data on the internet has been GC corrected). 

I could add some flags to ldsc for displaying liability scale h2 and genetic covariance. The logic would be something like this

```
--h2 --sample-prev 0.5 --pop-prev 0.01
```
(print h2 obs then h2 liab) 
```
--rg --sample-prev 0.5,0.5 --pop-prev 0.01,0.15
```
or if one trait is a QT (in which case genetic covariance is on the half-observed scale)
```
--rg --sample-prev 0.5,QT --pop-prev 0.01,QT
```
I think the --sample-prev flag is necessary -- right now sumstats_to_chisq.py allows you to use the --N flag with case/control data. Actually, even if you set --N-cas and --N-con (or if there are N_cas and N_con columns) it summarizes these into a single column

**Comment by pfsulliv** [comment]
that would work too … 



> On Jan 16, 2015, at 5:51 PM, Brendan Bulik-Sullivan <notifications@github.com> wrote:
> 
> This seems like something that would work better as a standalone script, rather than a feature of ldsc (also we haven't focused much on heritability estimation so far, because almost all of the public GWAS data on the internet has been GC corrected).
> 
> I could add some flags to ldsc for displaying liability scale h2 and genetic covariance. The logic would be something like this
> 
> --h2 --sample-prev 0.5 --pop-prev 0.01
> 
> (print h2 obs then h2 liab)
> 
> --rg --sample-prev 0.5,0.5 --pop-prev 0.01,0.15
> 
> or if one trait is a QT (in which case genetic covariance is on the half-observed scale)
> 
> --rg --sample-prev 0.5,QT --pop-prev 0.01,QT
> 
> I think the --sample-prev flag is necessary -- right now sumstats_to_chisq.py allows you to use the --N flag with case/control data. Actually, even if you set --N-cas and --N-con (or if there are N_cas and N_con columns) it summarizes these into a single column
> 
> —
> Reply to this email directly or view it on GitHub.
> 

[[[ pfs ]]]

**Comment by bulik** [comment]
added this to dev; will be a feature in v1.0.0. the only difference from what I described above is that if you are using --rg with one quantitative trait and one binary trait, you should do
```
--rg qt,cc --samp-prev nan,0.5, --pop-prev nan,0.01
```
There currently isn't a good way to do this with more than two arguments to --rg, but I'll add that later.
